* Adding check when every function is run

diff --git a/footer b/footer
--- a/footer
+++ b/footer
@@ -3,6 +3,11 @@ if [ $# = 0 ]; then
 	# run every verbfunc
 	for ((verbi=0;verbi<="${#verbs[*]}";verbi++)); do
 		${verbfuncs[$verbi]}
+		# if we get an exit code, bail
+		ret=$?
+		if [ $ret -gt 0 ]; then
+			exit $ret
+		fi
 	done
 	exit
 fi
